college/config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # method 'path' to: 'actionform controller'
  get 'student', to: "student#index"

  post 'student/sample', to: "student#create"

  get 'student/sample', to: "student#sample"

  get 'student/:id/edit', to: "student#edit", as: :edit_student

  get 'student/:id', to: "student#show", as: :std

  patch 'student/:id', to: "student#update", as: :update

  get 'student/:id/delete', to: "student#destroy", as: :delete_student

 
end   

college/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

college/app/models/student.rb
class Student < ApplicationRecord

end

college/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

college/app/controllers/student_controller.rb
class StudentController < ApplicationController
	before_action :set_student, only: [ :show, :edit, :update, :destroy ]


	def index
		@student = Student.all
		# detail ... .order('created_at DESC')
		# passing accessability to Student table to index.html.erb through the object collection  students
	end 

	def sample
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save 
			redirect_to @student, notice: "Information saved successfully "
		else
			render :sample, alert: "Your information wasnt saved! "
		end
	end

	def show 
		
	end

	def edit
		
	end

	def update
		if @student.update(student_params)
			redirect_to @student, notice: " Your post was updated successfully" 
		else
			render :edit, alert: "Your detail wasn't updated!"
		end
	end

	def destroy
		@student.destroy

		redirect_to student_path, notice: "One post deleted "

	end

	private 

	def set_student
		@student = Student.find(params[:id])
	end
 
	def student_params
		params.require(:student).permit(:name, :address)
	end

end
 

college/app/helpers/application_helper.rb
module ApplicationHelper
end

college/app/helpers/student_helper.rb
module StudentHelper
end

college/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>College</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

college/app/views/student/_form.html.erb
<%=  simple_form_for(@student) do |f| %>
	<%= f.input  :name %><br>
	<%= f.input  :address %><br>
	<%= f.submit %>
<% end %>  
<br>
<%= link_to "Back", student_path  %>

college/app/views/student/edit.html.erb
<h2><%= "Edit student detail here" %></h2>

<%=  simple_form_for(@student) do |f| %>
	<%= f.input  :name %><br>
	<%= f.input  :address %><br>
	<%= f.submit "Update Student" %>
<% end %>  
<br>
<%= link_to "Back", student_path  %>	

college/app/views/student/index.html.erb
<h1>Hello Students</h1>

<%= link_to "Entry form for student", student_sample_path %><br><br>

<!-- Showing the data from Student table  -->

<% @student.each do |student| %>
	<p>
		<%= "#{student.id}. #{student.name} "+" . . .  " %>
		<%= link_to "Show", std_path(student.id) %>
		<%# link_to "Edit", edit_student_path(student) %>
		<%= link_to "Delete", delete_student_path(student)%>
	</p> 
<% end %> 


<br><br>
<%= link_to " Enter Student Info", 
	{:controller => 'student',
		:action => 'sample'} %>

college/app/views/student/sample.html.erb
<h2>Welcome to Sample </h2>

<%= link_to " Go Index Page", { :controller=>'student', :action =>'index'} %>
<h2>Fill up the form below: </h2>


<%=  simple_form_for(:student) do |f| %>
	<%= f.input  :name %><br>
	<%= f.input  :address %><br>
	<%= f.submit %>
<% end %>  

college/app/views/student/show.html.erb
<h2> Details</h2>

<h4>Name: <%= @student.name %> </h4>
<p> <b>Address:</b>  <%= @student.address %></p>
<%= link_to "All student", student_path  %>