revise/config/routes.rb
Rails.application.routes.draw do

	# introducing the routing hierarchy

	get 'products', to: "products#index", as: :products

	# post 'products', to: "products#create"

	get 'products/:id', to: "products#show", as: :show_product
	
	get 'products/newp', to: "products#newp", as: :new_product
	
	get 'products/:id/edit', to: "products#edit", as: :edit_product
	
	patch 'products/:id', to: "products#update" 

	# put 'products/:id', to: "products#update"

	delete 'products/:id/delete', to: "products#destroy", as: :delete_product


end

revise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

revise/app/models/product.rb
class Product < ApplicationRecord
end

revise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

revise/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
  	@products = Product.all
  end

  def newp
  	@product = Product.new
  end

  def show
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to products_path, notice: "product added succcessfully"
  	else
  		render products_newp_path, alert: "product implication error"
  	end
  end

	def edit
 		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to products_path, notice: "Product updated succcessfully"
		else
			render "edit", alert: "Product hasn't been modified"
		end
	end 

  def destroy
  	@product = Product.find(params[:id])
  	@product.delete

  	redirect_to products_newp_path
  end




  private

  def product_params
  	params.require(:product).permit(:name, :price, :description)
  end


end

revise/app/helpers/application_helper.rb
module ApplicationHelper
end

revise/app/helpers/products_helper.rb
module ProductsHelper
end

revise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Revise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

revise/app/views/products/edit.html.erb
<h2>Edit the detail of <i>'<%= @product.name %></i>'</h2>
<hr>

<%= simple_form_for(:product, {:controller=>'products', :action=>'update'}, :method=>'patch') do |f| %>
	<%= f.input :name %><br>
	<%= f.input :price %><br>
	<%= f.input :description %><br>
	<%= f.submit "Update Product" %>
<% end %>
<br>
<hr>
<%= link_to "Home", products_path %>

revise/app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "Add Product", new_product_path %><hr>
<h2> <u>All Products</u></h2>


<table border="1">
	<tr><th>ID</th><th>Name</th><th>Price</th><th>Description</th><th>Operation</th></tr>

	<% @products.each do |p| %>
	<tr><td><%= p.id%></td><td><%= p.name %></td><td><%= p.price %></td><td><%= p.description %></td>
		<td>
			<%= link_to "Show", {:controller=>'products', 
				:action=>'show',
				:id=>p.id} %>
			<%= link_to "Delete", delete_product_path(p.id) %>
			<%= link_to "Edit", edit_product_path(p.id)%>
		</td></tr>
	<% end %>

</table>

	
	
	


 

revise/app/views/products/newp.html.erb
<h3>Enter new product here</h3>

<%= simple_form_for(@product) do |f| %>
	<%= f.input :name %><br>
	<%= f.input :price %><br>
	<%= f.input :description %><br>
	<%= f.submit %>
<% end %>
<br>

<%= link_to "Home", products_path %>

revise/app/views/products/show.html.erb
<h2>Product Name :<%= @product.name %></h2> 
<h3>Price: <%= @product.price %> </h3>
<p><%= @product.description %></p>
<hr>
<%= link_to "Home Page", products_path %>